### ISSUE TITLE
ERROR:onvif:Unexcept service type

### ISSUE THREAD

**Issue by codegastudio** [FalkTannhaeuser/python-onvif-zeep#5]
Hello,

After install thanks to 
>pip install --upgrade https://github.com/FalkTannhaeuser/python-onvif-zeep/archive/zeep.zip

I try to use your project but i get an error when i instantiate ONVIFCamera.

```
mycam = ONVIFCamera('ip', port, 'user', 'pass', '/path/to/wsdl/')
ERROR:onvif:Unexcept service type
Traceback (most recent call last):
  File "/path/lib/python3.4/site-packages/onvif/client.py", line 266, in update_xaddrs
    self.xaddrs[ns] = capability['XAddr']
TypeError: 'NoneType' object is not subscriptable
```

Regards

**Comment by CodyDeGhetto** [comment]
Same issue here as above.

Thanks

**Comment by FalkTannhaeuser** [comment]
As I explained in [another issue](https://github.com/FalkTannhaeuser/python-onvif-zeep/issues/4), when using Anaconda (at least under Windows), it is recommended to move the WSDL directory created during installation from e.g. `C:\ProgramData\Anaconda3\wsdl` manually to `C:\ProgramData\Anaconda3\Lib\site-packages\wsdl` (when using the root environment of Anaconda) respectively from `C:\ProgramData\Anaconda3\envs\<<<your Python env>>>\wsdl` to `C:\ProgramData\Anaconda3\envs\<<<your Python env>>>\Lib\site-packages\wsdl` (when using a virtual environment). *Yes, this should be explained in the installation instructions, or even better it should be fixed in the setup files...* After this, it should not longer be necessary to pass the 5<sup>th</sup> argument `'/path/to/wsdl/'` to the `ONVIFCamera` initialization.
Furthermore, the same questions as in said issue:
 * Which camera are you using? I did my tests on a Canon VB-H43.
 * Can you successfully run your tests with the [upstream project python-onvif](https://github.com/quatanium/python-onvif) under Python 2.7?

**Comment by CodyDeGhetto** [comment]
Geovision GV-EBD4700 and GV-ABL1300

I have not tried using Python 2.7 yet.
When I have time I will test it out.

Thank you.

**Comment by FalkTannhaeuser** [comment]
The commit 22f569e5447935f575fee7a0bdfb574264c755b1 should fix this warning.
